### ISSUE TITLE
update Socialmeta plugin issue

### ISSUE THREAD

**Issue by tramber91** [vistamedia/socialmeta#10]
Hi all
I'm with Joomla 3.7 and i have a warning in joomla update area about update of  Socialmeta plugin from version 1.0 utiil version 1.1.
When i manage automatic update, I have a sucess mesage

But unfortunatly the same warning about update from Socialmeta plugin from version 1.0 untiil version 1.1. is back even after update 

Same on your side ?

**Comment by ggppdk** [comment]
I don't get this behaviour

Also this is strange, there is no 1.1 version the update URL is:
https://raw.githubusercontent.com/vistamedia/socialmeta/master/updates/plg_socialmeta_updates.xml

And in the above XML the reported latest version is 1.0

**Comment by tramber91** [comment]
attached a screeshot

http://i.imgur.com/2fYExII.png

**Comment by ggppdk** [comment]
You seem to have some older update URL besides the correct One

Execute this query in PHPMyadmin
```SQL
SELECT * FROM `jos_update_sites` WHERE name like 'socialmeta%'
```
and you will probably get 2 entries:
"**Socialmeta plugin**"
"**Socialmeta GIT update stream**"

Delete only the entry "**Socialmeta plugin**", and error should be gone

If error is not gone, then you can try to delete all update URLs that start with "Socialmeta " 
and then Install from URL:
https://github.com/vistamedia/socialmeta/archive/master.zip

**Comment by tramber91** [comment]
it is ok now thanks
