### ISSUE TITLE
[Metadata] image n'est pas un type de cible valide connu pour la propriété image.

### ISSUE THREAD

**Issue by eric-lamy-agerix** [vistamedia/socialmeta#21]
Salut,

Noté aujourd'hui en passant une page sur le testeur de Google, voir copie écran
![2019-04-05_17h27_01](https://user-images.githubusercontent.com/3830166/55638873-7e90b800-57c8-11e9-9382-e686fee45c18.png)

**Comment by ggppdk** [comment]
Hi,
Can you also post this in English ?
As translating the text from the image is difficult

**Comment by vistamedia** [comment]
It should have been fixed with commit [482c73](https://github.com/vistamedia/socialmeta/commit/c482c73281500a44e6ffc2edf1b8d30cd34ddf05), thanks for reporting ;)
