### ISSUE TITLE
Thai language for socialmeta

### ISSUE THREAD

**Issue by lungkao** [vistamedia/socialmeta#4]
[th-TH.plg_system_socialmeta.zip](https://github.com/vistamedia/socialmeta/files/264241/th-TH.plg_system_socialmeta.zip)

**Comment by vistamedia** [comment]
Thanks Bubu :) I will add the file. You can send a pull request as well ;)

**Comment by vistamedia** [comment]
It done [in this commit](https://github.com/vistamedia/socialmeta/commit/1bf3822f33efd0e175077fd3652c78a1ad905802)
Thanks a lot my friend ;)
