### ISSUE TITLE
Google structured data testing tool fails : missing publisher

### ISSUE THREAD

**Issue by lllopo** [vistamedia/socialmeta#9]
Google structured data testing tool fails on the "ld+json" part with the message "	
A value for the publisher field is required.", while the publisher is present as an opengraph tag (but really missing in the json).

**Comment by lllopo** [comment]
Anyone ?

**Comment by ggppdk** [comment]
Can you provide more information on how to replicate this, maybe post a few pics too

**Comment by lllopo** [comment]
Test this "http://test.harmony-suites.info/" here "https://search.google.com/structured-data/testing-tool".
Basically the code genrated by your extension is :
{
    "@context":"http:\/\/schema.org\/",
    "@type":"Article",
    "image":{
        "@type":"ImageObject",
        "url":"http:\/\/test.harmony-suites.info\/images\/harmony\/logos\/logo_color.png",
        "width":965,
        "height":562,
        "fileFormat":"image\/png"
    },
    "mainEntityOfPage":"http:\/\/test.harmony-suites.info\/",
    "inLanguage":"ru-RU",
    "author":{"@type":"Person","name":"Harmony Suites"},
    "articleSection":"Uncategorised",
    "dateModified":"2016-06-08T14:16:32+0300",
    "datePublished":"2016-04-08T17:45:28+0300",
    "headline":"Some headline",
    "name":"Some name",
    "description":"Somedesc"
}

And the problem is, that it lacks the "publisher" property, which turns out to be mandatory. So the code above should have a publisher too. That's it.

Btw., in addition - a plugin option to include or not include the json microdata would be very welcome too.

**Comment by vistamedia** [comment]
Hi, that's pretty strange... Did you fill the google publisher field and choose the publisher logo?
![conf-google-plus](https://cloud.githubusercontent.com/assets/9335926/20339391/6181c460-abdc-11e6-8658-03b135f0c892.jpg)
You can check on this page for example:
http://pedalsteel.fr/index.php/repair
And the result here:
![socialmeta-amp](https://cloud.githubusercontent.com/assets/9335926/20339422/913b2b9c-abdc-11e6-931a-aae08b2a7cfb.jpg)
Cheer, Emmanuel.

**Comment by lllopo** [comment]
Nope. Isn't it enough to have the Facebook page and profile URL. I f the G+ data is necessary, then it is totally my misunderstanding.

**Comment by vistamedia** [comment]
No problem, I didn't document the google+ features yet. Google publisher and Facebook publisher are two separate things.
In order to get proper structured data you have to fill up the the google plus profile link and a logo (dimensions: 600x60)
Cheers, Emmanuel.

**Comment by lllopo** [comment]
Yeah, I laready sorted it out with the proper logo size and stuff. Thank you very much for the assistance.

**Comment by vistamedia** [comment]
My pleasure ;)
